# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ws < Formula
  desc "Witself CLI (ws)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.1/ws_0.0.1_darwin_amd64.tar.gz"
      sha256 "16f5c4b3aef3b5e1df5b82e741e822245f2d0319ec1b1a6e312f3a84fae22a3d"

      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.1/ws_0.0.1_darwin_arm64.tar.gz"
      sha256 "e545ba18f9a32259263174f8d82cdf4baaa9cc2fff8679b9583f9a9f8d2d9b0b"

      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.1/ws_0.0.1_linux_amd64.tar.gz"
      sha256 "35f529e185f8e8ade9854c9a9395fac36130aad6f9f37c1ebf7dfd8c05b0daa2"
      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.1/ws_0.0.1_linux_arm64.tar.gz"
      sha256 "1e5cdb399fa0f8c9af5fd8635a8362b48f1918e73b4ad7ba5717c78fb3171acd"
      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  test do
    system "#{bin}/ws", "version"
  end
end
