# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WitselfInfra < Formula
  desc "Witself cell infrastructure provisioner (Pulumi-Go via the Automation API)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.30"
  license "FSL-1.1-ALv2"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.30/witself-infra_0.0.30_darwin_amd64.tar.gz"
      sha256 "634ef1c957a7a41dd8da1b46fcc032e0c17fee14313d7bf7888bd124c83708e0"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.30/witself-infra_0.0.30_darwin_arm64.tar.gz"
      sha256 "d3651e984b86d021454d1cb6cdca977e912080f77da885c0e1b2bc2629d1b172"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.30/witself-infra_0.0.30_linux_amd64.tar.gz"
      sha256 "845fa997d85627ed148293d75b8c0d1e459b9cd9c83ae2c225e371f843933b02"
      define_method(:install) do
        bin.install "witself-infra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.30/witself-infra_0.0.30_linux_arm64.tar.gz"
      sha256 "cec37cc41b1f6c364e653012bfe63b77ab50677ca8757299e48c4e4a022a624f"
      define_method(:install) do
        bin.install "witself-infra"
      end
    end
  end

  test do
    system "#{bin}/witself-infra", "help"
  end
end
