# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Witself < Formula
  desc "Witself CLI"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.118"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.118/witself_0.0.118_darwin_amd64.tar.gz"
      sha256 "6f66ad17f6452581004570a02462f776c8673d00460659b17d85239def12f731"

      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.118/witself_0.0.118_darwin_arm64.tar.gz"
      sha256 "557c052f5c15a8b7cb171c8b191673a9d7177742a2af29fb1af7739e6898275a"

      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.118/witself_0.0.118_linux_amd64.tar.gz"
      sha256 "b4da82551af666cf9265e4974e45b71c9805897e11b16c3d0d6284f80fdcc16a"
      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.118/witself_0.0.118_linux_arm64.tar.gz"
      sha256 "25baedde0031892fc2dc56f858770f7457559f7d9792b177c25a45719465c15d"
      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  test do
    system "#{bin}/witself", "version"
  end
end
