# This file was generated by Witself release tooling. DO NOT EDIT.
class WitselfInfra < Formula
  desc "Cell infrastructure provisioner using the Pulumi Automation API"
  homepage "https://github.com/witwave-ai/witself"
  license "FSL-1.1-ALv2"

  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.294/witself-infra_0.0.294_darwin_amd64.tar.gz"
      sha256 "4d878880d8b6c5a2b1fa19e476084a27fd882b59224ce5dddf9e925871e44a1b"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.294/witself-infra_0.0.294_darwin_arm64.tar.gz"
      sha256 "e50197cbc74537a0a5599f7f1c6dac658cc530af234a93ccf10e1d2238fb5121"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.294/witself-infra_0.0.294_linux_amd64.tar.gz"
      sha256 "9622f906aa95d9c694bf28a0cee6c4503df3b6e10d758ae14e47ee6f80d59f9e"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.294/witself-infra_0.0.294_linux_arm64.tar.gz"
      sha256 "d612f8cbbbb842a359797cf29dced818c97f6ccdc6900b0c0e627a29c796cd3b"

      define_method(:install) do
        bin.install "witself-infra"
      end
    end
  end

  test do
    system bin/"witself-infra", "help"
  end
end
