# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Witself < Formula
  desc "Witself CLI"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.124"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.124/witself_0.0.124_darwin_amd64.tar.gz"
      sha256 "3a9a17fad1b77550ac67c2a8fd30c79c0d067f5199884e8a28b79514591bd0ce"

      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.124/witself_0.0.124_darwin_arm64.tar.gz"
      sha256 "941d4b8b79bb84adea027538fd44cb49c341f7e7cd60ee43b6f4ff5073134cbe"

      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.124/witself_0.0.124_linux_amd64.tar.gz"
      sha256 "fdacb14997d6e154d21ebc60da51632c5be953b165984cf94b255fd039e44b3a"
      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.124/witself_0.0.124_linux_arm64.tar.gz"
      sha256 "3b8e5b49e2cdd8883a9c61e883f35d5906bb698b26b341443d423683c9b7b655"
      define_method(:install) do
        bin.install "witself"
        # Muscle-memory alias: `ws` keeps working forever.
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  test do
    system "#{bin}/witself", "version"
  end
end
