# This file was generated by Witself release tooling. DO NOT EDIT.
class WitselfAdmin < Formula
  desc "Fleet administration CLI for the Witself control plane"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.271"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.271/witself-admin_0.0.271_darwin_amd64.tar.gz"
      sha256 "08032e4d65b18ab9d080193d70302f882fe9d8fd204d88cf19002b8a55f03be5"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.271/witself-admin_0.0.271_darwin_arm64.tar.gz"
      sha256 "9987954ee477909ad35e7fc2a3272ec6c5ce7502b6873889ad7f0a314a0ca695"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.271/witself-admin_0.0.271_linux_amd64.tar.gz"
      sha256 "253ecd2035b306f7757b93ea45215b9df56863354289040114cac44097950971"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.271/witself-admin_0.0.271_linux_arm64.tar.gz"
      sha256 "9b97e2976ee00567894ae284b8de4d40ea845a27563fe3afebf641e53283c3cb"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
  end

  test do
    system bin/"witself-admin", "version"
  end
end
