# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WitselfAdmin < Formula
  desc "Witself fleet-admin CLI (talks only to the Witself control plane)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.144"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.144/witself-admin_0.0.144_darwin_amd64.tar.gz"
      sha256 "67a5828c275ed64078f0a942845a75c907120a48a00a69edf98d7c511f3bbe9d"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.144/witself-admin_0.0.144_darwin_arm64.tar.gz"
      sha256 "56b2173bcf0c1a7165e1fc9d5d0e578b1db572212eab78c3f59ca26ad9318d7d"

      define_method(:install) do
        bin.install "witself-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.144/witself-admin_0.0.144_linux_amd64.tar.gz"
      sha256 "afd6a950cb5a49e096e88627006f1924f45d2a1f3c60ebc1e7a589ed0571b759"
      define_method(:install) do
        bin.install "witself-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.144/witself-admin_0.0.144_linux_arm64.tar.gz"
      sha256 "b5a8eeda5b9619589b6d1aae6ea89c661e7cfd809bdecb2e8564649b4d24e3b3"
      define_method(:install) do
        bin.install "witself-admin"
      end
    end
  end

  test do
    system "#{bin}/witself-admin", "version"
  end
end
