# This file was generated by Witself release tooling. DO NOT EDIT.
class Witself < Formula
  desc "Identity, memory, messaging, and secrets CLI for autonomous AI agents"
  homepage "https://github.com/witwave-ai/witself"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.287/witself_0.0.287_darwin_amd64.tar.gz"
      sha256 "fc7b9f3f14df1286c72926a9b89781d2d5a58d7e027e590edaa72d57895f925a"

      define_method(:install) do
        bin.install "witself"
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.287/witself_0.0.287_darwin_arm64.tar.gz"
      sha256 "0e5b9cee56d7ada1003bf4119805921b2430f0b9cb65515068cbed0b03bbdec6"

      define_method(:install) do
        bin.install "witself"
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.287/witself_0.0.287_linux_amd64.tar.gz"
      sha256 "06965d7794fd44d71d60cff003893d9067c3b73925f016aa0b5844dcef3dce3a"

      define_method(:install) do
        bin.install "witself"
        bin.install_symlink "witself" => "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.287/witself_0.0.287_linux_arm64.tar.gz"
      sha256 "d7316db1e4e169739749002822c5a3b81f8582ecb2ec40735a78764e99897340"

      define_method(:install) do
        bin.install "witself"
        bin.install_symlink "witself" => "ws"
      end
    end
  end

  test do
    system bin/"witself", "version"
  end
end
