# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WitwaveAdmin < Formula
  desc "Witwave fleet-admin CLI (talks only to the Witself control plane)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.91"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.91/witwave-admin_0.0.91_darwin_amd64.tar.gz"
      sha256 "12c969b285c7b80e88cbfd2abf430885a2e1afe73bb57ddd99affc812e85f6f2"

      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.91/witwave-admin_0.0.91_darwin_arm64.tar.gz"
      sha256 "f3ae52552989688cf1b963aaf29eee85eadd90fafdea49b30e0dd8a9538e84a5"

      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.91/witwave-admin_0.0.91_linux_amd64.tar.gz"
      sha256 "4d5b8baff9f417a6521e83d5bcc92acb13bd45c24f873dad196ec42af3f69e17"
      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.91/witwave-admin_0.0.91_linux_arm64.tar.gz"
      sha256 "c61dc0e24c6c4f197209dc96418b99bd205bffa2fe22dedae0c0bee48e26181c"
      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
  end

  test do
    system "#{bin}/witwave-admin", "version"
  end
end
