# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WitwaveAdmin < Formula
  desc "Witwave fleet-admin CLI (talks only to the Witself control plane)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.89"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.89/witwave-admin_0.0.89_darwin_amd64.tar.gz"
      sha256 "309c423f34dcb7ef3b18fe8da255309be9533fc07e4e72b3f6cda54aad6a6c3d"

      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.89/witwave-admin_0.0.89_darwin_arm64.tar.gz"
      sha256 "01cfd953c71c019e6d7a7e61d18c89d22b092063ea6eeae03c97c58a2a51b93c"

      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.89/witwave-admin_0.0.89_linux_amd64.tar.gz"
      sha256 "fb932ba037dd59124d015b51410aa4adf8e451b85d12d73683898be10e86ab2c"
      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.89/witwave-admin_0.0.89_linux_arm64.tar.gz"
      sha256 "56349996341a5413afedf6531d0f94d3eef5535f021d8da8408b3ba7d74184e2"
      define_method(:install) do
        bin.install "witwave-admin"
      end
    end
  end

  test do
    system "#{bin}/witwave-admin", "version"
  end
end
