# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ws < Formula
  desc "Witself CLI (ws)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.20"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.20/ws_0.0.20_darwin_amd64.tar.gz"
      sha256 "b58a74ba2f606a6bdeede1c480c34db1305c457b5514f221f1e57b42951b3ba0"

      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.20/ws_0.0.20_darwin_arm64.tar.gz"
      sha256 "81ceb9e1599d4a75a1823fc9f90b41b6154f1f5aada131cf0f63fdf76dcafb69"

      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.20/ws_0.0.20_linux_amd64.tar.gz"
      sha256 "6e66c10a85c01095c2c11dfd825fe159246977c10304af67596e8f91343aa434"
      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.20/ws_0.0.20_linux_arm64.tar.gz"
      sha256 "892b62b239ac8bbafee8baad9293c772b90dbeacd28d20b6b0fcf9211e6c7c5d"
      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  test do
    system "#{bin}/ws", "version"
  end
end
