# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ws < Formula
  desc "Witself CLI (ws)"
  homepage "https://github.com/witwave-ai/witself"
  version "0.0.22"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.22/ws_0.0.22_darwin_amd64.tar.gz"
      sha256 "046e0e6c8aa5ac4663fe48239ef9dcb445ad83c5760d9e021173bbcda77adaab"

      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.22/ws_0.0.22_darwin_arm64.tar.gz"
      sha256 "d361487d95a5592a97bf62c565865c7de42c9e96ab140cf2a4ae390f58f653ae"

      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.22/ws_0.0.22_linux_amd64.tar.gz"
      sha256 "94d39b7cfeb29cc58445490f64208b551c39a90b72b606d6123b8784aa17f273"
      define_method(:install) do
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/witwave-ai/witself/releases/download/v0.0.22/ws_0.0.22_linux_arm64.tar.gz"
      sha256 "0af755af565e59ec5672fabf7862c27599f09282860de21231c7eb55c26afbd1"
      define_method(:install) do
        bin.install "ws"
      end
    end
  end

  test do
    system "#{bin}/ws", "version"
  end
end
